# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import learn.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=225)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=7)),
                ('width', models.IntegerField(blank=True, default=500, help_text='Enter positive value ')),
                ('height', models.IntegerField(blank=True, default=500, help_text='Enter positive value ')),
                ('flip', models.CharField(choices=[('horizon', 'Flip Horizontally'), ('vertical', 'Flip Vertically'), ('NONE', 'None')], default='NONE', max_length=17)),
                ('rotate', models.CharField(choices=[('clock', 'Clockwise'), ('anti', 'Anticlockwise'), ('NONE', 'None')], default='NONE', max_length=15)),
                ('blur', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=5)),
                ('effect', models.IntegerField(choices=[(1, 'None'), (2, 'Aqua'), (3, 'Seaform'), (4, 'Grayscale'), (5, 'Retro'), (6, 'Edges'), (7, 'Negative'), (8, 'Sepia')], default=1)),
                ('document', models.ImageField(upload_to=learn.models.get_file_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('like_or_not', models.IntegerField(default=0)),
                ('like_user', models.ManyToManyField(blank=True, related_name='hello', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, object),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=100)),
                ('Last_Name', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=30)),
                ('DOB', models.DateTimeField(blank=True, null=True)),
                ('profile_pic', models.ImageField(default='profile_pic/default_profile.jpg', upload_to=learn.models.get_profile_name)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Document'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
