# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180203_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.BinaryField(),
        ),
    ]
