# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20180204_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to=''),
        ),
    ]
