# Generated by Django 2.0.2 on 2019-01-03 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0008_file_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Filelo',
        ),
        migrations.RenameField(
            model_name='filelo',
            old_name='document',
            new_name='files',
        ),
    ]
