# Generated by Django 2.0.2 on 2019-01-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20190103_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelo',
            name='user',
        ),
    ]
