# Generated by Django 2.0.2 on 2019-01-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_remove_filelo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filelo',
        ),
    ]
