# Generated by Django 2.0.2 on 2019-01-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_delete_filelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
            ],
            bases=(models.Model, object),
        ),
    ]
